import { Injectable, NotFoundException } from '@nestjs/common';
import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { PatchStageDto } from './dto/patch-stage.dto';
import { PatchRunDto } from './dto/patch-run.dto';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';
import { marked } from 'marked';
import sanitizeHtml from 'sanitize-html';
import {
  Document,
  Packer,
  Paragraph,
  HeadingLevel,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  ShadingType,
  LevelFormat,
  AlignmentType,
  Header,
  Footer,
} from 'docx';

export function resolveExportDir(customExportPath?: string): string {
  const home = os.homedir();

  if (customExportPath && customExportPath.trim()) {
    const resolved = path.resolve(customExportPath.trim());
    // Prevent path traversal — export must be within user's home directory
    if (!resolved.startsWith(home + path.sep) && resolved !== home) {
      throw new Error(`Export path must be within your home directory (${home}). Got: ${resolved}`);
    }
    return resolved;
  }

  const oneDriveDesktop = path.join(home, 'OneDrive', 'Desktop');
  const regularDesktop = path.join(home, 'Desktop');
  return fs.existsSync(oneDriveDesktop) ? oneDriveDesktop : regularDesktop;
}

const REPORT_HTML_TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{TITLE}} — Feasibility Report</title>
<style>
*{box-sizing:border-box;margin:0;padding:0}
body{background:#030712;color:#f3f4f6;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:15px;line-height:1.7;padding:2rem;max-width:900px;margin:0 auto}
h1{font-size:1.75rem;font-weight:700;color:#60a5fa;border-bottom:1px solid #374151;padding-bottom:.5rem;margin:1.5rem 0 .75rem}
h2{font-size:1.4rem;font-weight:600;color:#93c5fd;border-bottom:1px solid #1f2937;padding-bottom:.25rem;margin:1.25rem 0 .5rem}
h3{font-size:1.2rem;font-weight:600;color:#c4b5fd;margin:1rem 0 .5rem}
h4{font-size:1rem;font-weight:600;color:#e5e7eb;margin:.75rem 0 .25rem}
p{color:#d1d5db;margin:.5rem 0}
ul{list-style:disc;margin:.5rem 0 .5rem 1.5rem;color:#d1d5db}
ol{list-style:decimal;margin:.5rem 0 .5rem 1.5rem;color:#d1d5db}
li{margin-bottom:.25rem}
table{width:100%;border-collapse:collapse;font-size:.875rem;margin:1rem 0}
th{background:#1f2937;color:#93c5fd;font-weight:600;padding:.5rem .75rem;text-align:left;border:1px solid #374151}
td{padding:.5rem .75rem;border:1px solid #1f2937;color:#d1d5db}
tr:nth-child(even) td{background:#111827}
code{background:#1f2937;color:#93c5fd;padding:.1rem .35rem;border-radius:4px;font-size:.85em;font-family:'Courier New',monospace}
pre{background:#1f2937;border-radius:6px;padding:1rem;overflow-x:auto;margin:.75rem 0}
pre code{background:transparent;padding:0;color:#d1d5db}
hr{border:none;border-top:1px solid #374151;margin:1.25rem 0}
strong{color:#f9fafb;font-weight:600}
em{color:#9ca3af;font-style:italic}
blockquote{border-left:4px solid #3b82f6;padding:.5rem 1rem;background:rgba(31,41,55,.5);margin:.75rem 0;color:#9ca3af;font-style:italic}
a{color:#60a5fa;text-decoration:underline}a:hover{color:#93c5fd}
</style>
</head>
<body>
{{BODY}}
<hr style="margin-top:3rem">
<p style="font-size:.8rem;color:#6b7280;line-height:1.5;margin-top:1rem">
<strong style="color:#9ca3af">Disclaimer:</strong> This report was generated by PatentForge, an open-source AI-powered patent landscape research tool. It is intended for informational and educational purposes only. This report does not constitute legal advice. Before making any filing, licensing, enforcement, or investment decisions, consult a registered patent attorney.
</p>
</body>
</html>`;

const THIN_BORDER = { style: BorderStyle.SINGLE, size: 4, color: 'AAAAAA' };
const TABLE_BORDERS = {
  top: THIN_BORDER,
  bottom: THIN_BORDER,
  left: THIN_BORDER,
  right: THIN_BORDER,
  insideH: THIN_BORDER,
  insideV: THIN_BORDER,
};

/**
 * Parse inline markdown formatting into docx TextRuns.
 * Handles: **bold**, *italic* / _italic_, and `inline code`.
 */
export function parseInlineRuns(text: string): TextRun[] {
  // Regex matches: **bold**, *italic*, _italic_, `code`, or plain text
  const TOKEN_RE = /(\*\*.*?\*\*|\*[^*]+?\*|_[^_]+?_|`[^`]+?`)/g;
  const runs: TextRun[] = [];
  let lastIndex = 0;

  for (const match of text.matchAll(TOKEN_RE)) {
    // Add plain text before this match
    if (match.index! > lastIndex) {
      runs.push(new TextRun({ text: text.slice(lastIndex, match.index!) }));
    }

    const token = match[0];
    if (token.startsWith('**') && token.endsWith('**')) {
      runs.push(new TextRun({ text: token.slice(2, -2), bold: true }));
    } else if (token.startsWith('`') && token.endsWith('`')) {
      runs.push(new TextRun({ text: token.slice(1, -1), font: { name: 'Consolas' }, size: 18 }));
    } else if ((token.startsWith('*') && token.endsWith('*')) || (token.startsWith('_') && token.endsWith('_'))) {
      runs.push(new TextRun({ text: token.slice(1, -1), italics: true }));
    }

    lastIndex = match.index! + token.length;
  }

  // Trailing plain text
  if (lastIndex < text.length) {
    runs.push(new TextRun({ text: text.slice(lastIndex) }));
  }

  // If no formatting found, return the whole string as a plain run
  if (runs.length === 0) {
    runs.push(new TextRun({ text }));
  }

  return runs;
}

function parseTableLines(tableLines: string[]): Table {
  const rows: TableRow[] = [];
  let isFirstDataRow = true;
  for (const line of tableLines) {
    // Skip separator rows like |---|---|
    if (/^\|[\s\-:|]+\|$/.test(line.trim())) continue;
    const cells = line
      .split('|')
      .slice(1, -1)
      .map((c) => c.trim());
    const isHeader = isFirstDataRow;
    isFirstDataRow = false;
    rows.push(
      new TableRow({
        tableHeader: isHeader,
        children: cells.map(
          (cellText) =>
            new TableCell({
              borders: TABLE_BORDERS,
              shading: isHeader ? { type: ShadingType.SOLID, color: '2D3748' } : undefined,
              children: [new Paragraph({ children: parseInlineRuns(cellText.replace(/`(.*?)`/g, '$1')) })],
              width: { size: Math.floor(9000 / cells.length), type: WidthType.DXA },
            }),
        ),
      }),
    );
  }
  return new Table({ rows, width: { size: 9000, type: WidthType.DXA }, borders: TABLE_BORDERS });
}

/** Numbering config for ordered lists (used in Document constructor). */
export const ORDERED_LIST_NUMBERING = {
  config: [
    {
      reference: 'ordered-list',
      levels: [
        {
          level: 0,
          format: LevelFormat.DECIMAL,
          text: '%1.',
          alignment: AlignmentType.START,
        },
      ],
    },
  ],
};

/**
 * Parse a full markdown string into docx Paragraph and Table elements.
 * Handles: headers, bold, italic, inline code, bullets (nested), numbered lists, tables.
 */
export function parseMarkdownToDocxParagraphs(markdown: string): (Paragraph | Table)[] {
  const lines = markdown.split('\n');
  const elements: (Paragraph | Table)[] = [];
  let tableBuffer: string[] = [];

  function flushTable() {
    if (tableBuffer.length > 0) {
      elements.push(parseTableLines(tableBuffer));
      elements.push(new Paragraph({ text: '' }));
      tableBuffer = [];
    }
  }

  for (const line of lines) {
    if (line.trimStart().startsWith('|')) {
      tableBuffer.push(line);
      continue;
    }
    flushTable();

    if (line.startsWith('# ')) {
      elements.push(new Paragraph({ text: line.slice(2), heading: HeadingLevel.HEADING_1 }));
    } else if (line.startsWith('## ')) {
      elements.push(new Paragraph({ text: line.slice(3), heading: HeadingLevel.HEADING_2 }));
    } else if (line.startsWith('### ')) {
      elements.push(new Paragraph({ text: line.slice(4), heading: HeadingLevel.HEADING_3 }));
    } else if (line.startsWith('#### ')) {
      elements.push(new Paragraph({ text: line.slice(5), heading: HeadingLevel.HEADING_4 }));
    } else if (/^\s{2,}[-*]\s/.test(line)) {
      // Nested bullet (2+ spaces before - or *)
      const text = line.replace(/^\s+[-*]\s/, '');
      elements.push(new Paragraph({ children: parseInlineRuns(text), bullet: { level: 1 } }));
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      elements.push(new Paragraph({ children: parseInlineRuns(line.slice(2)), bullet: { level: 0 } }));
    } else if (/^\d+\.\s/.test(line)) {
      // Numbered list item
      const text = line.replace(/^\d+\.\s/, '');
      elements.push(
        new Paragraph({
          children: parseInlineRuns(text),
          numbering: { reference: 'ordered-list', level: 0 },
        }),
      );
    } else if (line.startsWith('> ')) {
      const text = line.slice(2);
      elements.push(
        new Paragraph({
          children: parseInlineRuns(text),
          indent: { left: 720 },
        }),
      );
    } else if (line.trim() === '' || line.startsWith('---')) {
      elements.push(new Paragraph({ text: '' }));
    } else {
      elements.push(new Paragraph({ children: parseInlineRuns(line) }));
    }
  }
  flushTable();
  return elements;
}

export const STAGE_NAMES = [
  'Technical Intake & Restatement',
  'Prior Art Research',
  'Patentability Analysis',
  'Deep Dive Analysis',
  'IP Strategy & Recommendations',
  'Comprehensive Report',
];

@Injectable()
export class FeasibilityService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Calculate total cost across all completed feasibility stages for a project.
   * Used for server-side cost cap enforcement.
   */
  /**
   * Return average token counts per stage from historical runs,
   * or static fallback values if no completed runs exist.
   */
  async getCostEstimate(projectId: string) {
    const completedRuns = await this.prisma.feasibilityRun.findMany({
      where: { projectId, status: 'COMPLETE' },
      include: {
        stages: {
          where: { status: 'COMPLETE', inputTokens: { not: null }, outputTokens: { not: null } },
          select: { inputTokens: true, outputTokens: true, estimatedCostUsd: true },
        },
      },
    });

    const allStages = completedRuns.flatMap((r) => r.stages);
    if (allStages.length > 0) {
      const avgInput = Math.round(allStages.reduce((s, st) => s + (st.inputTokens ?? 0), 0) / allStages.length);
      const avgOutput = Math.round(allStages.reduce((s, st) => s + (st.outputTokens ?? 0), 0) / allStages.length);
      const avgCostPerStage = allStages.reduce((s, st) => s + (st.estimatedCostUsd ?? 0), 0) / allStages.length;
      return {
        hasHistory: true,
        runsUsed: completedRuns.length,
        stagesUsed: allStages.length,
        avgInputTokens: avgInput,
        avgOutputTokens: avgOutput,
        avgCostPerStage,
      };
    }

    // Static fallback — derived from actual Haiku run data
    return {
      hasHistory: false,
      runsUsed: 0,
      stagesUsed: 0,
      avgInputTokens: 19500,
      avgOutputTokens: 3500,
      avgCostPerStage: 0,
    };
  }

  /**
   * Return just the report text — lightweight endpoint for the report view.
   * Returns finalReport, or falls back to stage 6 output.
   */
  async getProjectTitle(projectId: string): Promise<string> {
    const project = await this.prisma.project.findUnique({ where: { id: projectId }, select: { title: true } });
    return project?.title ?? 'Patent Project';
  }

  /**
   * Return a complete styled HTML page for the feasibility report.
   * Used for inline viewing (report/html) and download (export/html).
   */
  async getReportHtmlPage(projectId: string): Promise<string> {
    const { report } = await this.getReportText(projectId);
    if (!report) return '<html><body><p>No report available.</p></body></html>';
    const title = await this.getProjectTitle(projectId);
    const body = sanitizeHtml(marked(report) as string);
    return REPORT_HTML_TEMPLATE.replace('{{TITLE}}', title.replace(/</g, '&lt;')).replace('{{BODY}}', body);
  }

  async getReportText(projectId: string) {
    const run = await this.prisma.feasibilityRun.findFirst({
      where: { projectId, status: 'COMPLETE' },
      orderBy: { version: 'desc' },
      select: { id: true, finalReport: true },
    });
    if (!run) return { report: null, html: null };

    let reportText = run.finalReport;
    if (!reportText) {
      const stage6 = await this.prisma.feasibilityStage.findFirst({
        where: { feasibilityRunId: run.id, stageNumber: 6, status: 'COMPLETE' },
        select: { outputText: true },
      });
      reportText = stage6?.outputText ?? null;
    }
    if (!reportText) return { report: null, html: null };

    // Pre-render HTML server-side so the browser doesn't have to parse markdown.
    // sanitize-html strips script tags and event handlers from AI-generated content.
    const html = sanitizeHtml(marked(reportText) as string);
    return { report: reportText, html };
  }

  async getProjectCumulativeCost(projectId: string): Promise<number> {
    // Aggregate costs across ALL cost-bearing tables, not just feasibility stages.
    // FeasibilityStage costs are nested under FeasibilityRun → projectId.
    const stages = await this.prisma.feasibilityStage.findMany({
      where: {
        feasibilityRun: { projectId },
        estimatedCostUsd: { not: null },
      },
      select: { estimatedCostUsd: true },
    });
    // ComplianceCheck costs are stored directly on the check record.
    const complianceChecks = await this.prisma.complianceCheck.findMany({
      where: { projectId, estimatedCostUsd: { not: null } },
      select: { estimatedCostUsd: true },
    });
    // PatentApplication costs are stored directly on the application record.
    const applications = await this.prisma.patentApplication.findMany({
      where: { projectId, estimatedCostUsd: { not: null } },
      select: { estimatedCostUsd: true },
    });
    // ClaimDraft costs are now stored after schema migration adding estimatedCostUsd.
    const claimDrafts = await this.prisma.claimDraft.findMany({
      where: { projectId, estimatedCostUsd: { not: null } },
      select: { estimatedCostUsd: true },
    });
    return (
      stages.reduce((sum, s) => sum + (s.estimatedCostUsd ?? 0), 0) +
      complianceChecks.reduce((sum, c) => sum + (c.estimatedCostUsd ?? 0), 0) +
      applications.reduce((sum, a) => sum + (a.estimatedCostUsd ?? 0), 0) +
      claimDrafts.reduce((sum, d) => sum + (d.estimatedCostUsd ?? 0), 0)
    );
  }

  /**
   * Fetch the invention description for a project.
   * Returns null if no invention input exists.
   */
  async getInventionDescription(projectId: string): Promise<string | null> {
    const invention = await this.prisma.inventionInput.findUnique({
      where: { projectId },
      select: { description: true },
    });
    return invention?.description ?? null;
  }

  async startRun(projectId: string) {
    const project = await this.prisma.project.findUnique({ where: { id: projectId } });
    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const existingCount = await this.prisma.feasibilityRun.count({
      where: { projectId },
    });
    const version = existingCount + 1;

    const run = await this.prisma.feasibilityRun.create({
      data: {
        projectId,
        version,
        status: 'PENDING',
        startedAt: new Date(),
        stages: {
          create: STAGE_NAMES.map((stageName, index) => ({
            stageNumber: index + 1,
            stageName,
            status: 'PENDING',
          })),
        },
      },
      include: {
        stages: {
          orderBy: { stageNumber: 'asc' },
        },
      },
    });

    await this.prisma.project.update({
      where: { id: projectId },
      data: { status: 'FEASIBILITY' },
    });

    return run;
  }

  /**
   * Create a new FeasibilityRun that copies completed stages from the prior run
   * up to fromStage-1, and sets stages fromStage..6 to PENDING for re-execution.
   */
  async rerunFromStage(projectId: string, fromStage: number) {
    if (fromStage < 1 || fromStage > 6) {
      throw new Error('fromStage must be between 1 and 6');
    }

    // Find the latest run
    const latestRun = await this.prisma.feasibilityRun.findFirst({
      where: { projectId },
      orderBy: { version: 'desc' },
      include: { stages: { orderBy: { stageNumber: 'asc' } } },
    });

    if (!latestRun) {
      throw new NotFoundException('No prior run found to re-run from');
    }

    // Validate that stages before fromStage are complete
    for (let i = 1; i < fromStage; i++) {
      const stage = latestRun.stages.find((s) => s.stageNumber === i);
      if (!stage || stage.status !== 'COMPLETE' || !stage.outputText) {
        throw new Error(`Stage ${i} must be complete before re-running from Stage ${fromStage}`);
      }
    }

    const version = latestRun.version + 1;

    // Build stage create data — copy completed, set pending for the rest
    const stageData = STAGE_NAMES.map((stageName, index) => {
      const stageNum = index + 1;
      if (stageNum < fromStage) {
        // Copy from prior run
        const priorStage = latestRun.stages.find((s) => s.stageNumber === stageNum)!;
        return {
          stageNumber: stageNum,
          stageName,
          status: 'COMPLETE' as const,
          outputText: priorStage.outputText,
          model: priorStage.model,
          webSearchUsed: priorStage.webSearchUsed,
          startedAt: priorStage.startedAt,
          completedAt: priorStage.completedAt,
          inputTokens: priorStage.inputTokens,
          outputTokens: priorStage.outputTokens,
          estimatedCostUsd: priorStage.estimatedCostUsd,
        };
      }
      return {
        stageNumber: stageNum,
        stageName,
        status: 'PENDING' as const,
      };
    });

    const run = await this.prisma.feasibilityRun.create({
      data: {
        projectId,
        version,
        status: 'RUNNING',
        startedAt: new Date(),
        stages: { create: stageData },
      },
      include: { stages: { orderBy: { stageNumber: 'asc' } } },
    });

    return run;
  }

  async getLatest(projectId: string) {
    const project = await this.prisma.project.findUnique({ where: { id: projectId } });
    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const run = await this.prisma.feasibilityRun.findFirst({
      where: { projectId },
      orderBy: { version: 'desc' },
      include: {
        stages: {
          orderBy: { stageNumber: 'asc' },
        },
      },
    });

    if (!run) {
      throw new NotFoundException(`No feasibility runs found for project ${projectId}`);
    }

    // Auto-heal: if run is stuck as RUNNING/ERROR but all stages are COMPLETE,
    // fix the run status on read. Also backfill finalReport if missing.
    const allStagesComplete = run.stages.length === 6 && run.stages.every((s) => s.status === 'COMPLETE');
    const needsStatusFix = run.status !== 'COMPLETE' && allStagesComplete;
    const needsReportFix = run.status === 'COMPLETE' && !run.finalReport && allStagesComplete;
    if (needsStatusFix || needsReportFix) {
      await this.checkAndCompleteRun(run.id);
      return this.prisma.feasibilityRun.findUnique({
        where: { id: run.id },
        include: { stages: { orderBy: { stageNumber: 'asc' } } },
      });
    }

    return run;
  }

  async getByVersion(projectId: string, version: number) {
    const project = await this.prisma.project.findUnique({ where: { id: projectId } });
    if (!project) {
      throw new NotFoundException(`Project ${projectId} not found`);
    }

    const run = await this.prisma.feasibilityRun.findFirst({
      where: { projectId, version },
      include: {
        stages: {
          orderBy: { stageNumber: 'asc' },
        },
      },
    });

    if (!run) {
      throw new NotFoundException(`Feasibility run version ${version} not found for project ${projectId}`);
    }

    return run;
  }

  async patchStage(projectId: string, stageNumber: number, dto: PatchStageDto) {
    let run;
    if (dto.runId) {
      run = await this.prisma.feasibilityRun.findUnique({ where: { id: dto.runId } });
    } else {
      run = await this.prisma.feasibilityRun.findFirst({
        where: { projectId },
        orderBy: { version: 'desc' },
      });
    }

    if (!run) {
      throw new NotFoundException(`No feasibility runs found for project ${projectId}`);
    }

    const stage = await this.prisma.feasibilityStage.findFirst({
      where: { feasibilityRunId: run.id, stageNumber },
    });

    if (!stage) {
      throw new NotFoundException(`Stage ${stageNumber} not found`);
    }

    const updateData: Prisma.FeasibilityStageUpdateInput = {};
    if (dto.status !== undefined) updateData.status = dto.status;
    if (dto.outputText !== undefined) updateData.outputText = dto.outputText;
    if (dto.model !== undefined) updateData.model = dto.model;
    if (dto.webSearchUsed !== undefined) updateData.webSearchUsed = dto.webSearchUsed;
    if (dto.errorMessage !== undefined) updateData.errorMessage = dto.errorMessage;
    if (dto.startedAt !== undefined) updateData.startedAt = new Date(dto.startedAt);
    if (dto.completedAt !== undefined) updateData.completedAt = new Date(dto.completedAt);
    if (dto.inputTokens !== undefined) updateData.inputTokens = dto.inputTokens;
    if (dto.outputTokens !== undefined) updateData.outputTokens = dto.outputTokens;
    if (dto.estimatedCostUsd !== undefined) updateData.estimatedCostUsd = dto.estimatedCostUsd;

    const updated = await this.prisma.feasibilityStage.update({
      where: { id: stage.id },
      data: updateData,
    });

    // Auto-complete: if this stage was marked COMPLETE, check if all 6 are done.
    // This handles the case where the SSE stream breaks but all stages finished.
    if (dto.status === 'COMPLETE') {
      await this.checkAndCompleteRun(run.id);
    }

    return updated;
  }

  /**
   * Check if all 6 stages of a run are COMPLETE. If so, mark the run COMPLETE
   * and generate finalReport from stage 6 output. This is the safety net for
   * when the SSE stream breaks — stages complete individually but the run-level
   * status never gets updated.
   */
  private async checkAndCompleteRun(runId: string) {
    const run = await this.prisma.feasibilityRun.findUnique({
      where: { id: runId },
      include: { stages: { orderBy: { stageNumber: 'asc' } } },
    });
    if (!run) return;
    // Skip only if COMPLETE and has a report — otherwise heal
    if (run.status === 'COMPLETE' && run.finalReport) return;

    const allComplete = run.stages.length === 6 && run.stages.every((s) => s.status === 'COMPLETE');
    if (!allComplete) return;

    // All 6 stages done — mark run COMPLETE with stage 6 as the report
    const stage6 = run.stages.find((s) => s.stageNumber === 6);
    const finalReport = run.finalReport || stage6?.outputText || null;

    await this.prisma.feasibilityRun.update({
      where: { id: runId },
      data: {
        status: 'COMPLETE',
        completedAt: new Date(),
        finalReport,
      },
    });
    console.log(`[Feasibility] Auto-completed run ${runId} — all 6 stages finished`);
  }

  async patchRun(projectId: string, dto: PatchRunDto) {
    let run;
    if (dto.runId) {
      run = await this.prisma.feasibilityRun.findUnique({ where: { id: dto.runId } });
    } else {
      run = await this.prisma.feasibilityRun.findFirst({
        where: { projectId },
        orderBy: { version: 'desc' },
      });
    }

    if (!run) {
      throw new NotFoundException(`No feasibility runs found for project ${projectId}`);
    }

    const updateData: Prisma.FeasibilityRunUpdateInput = {};
    if (dto.status !== undefined) {
      updateData.status = dto.status;
      if (dto.status === 'COMPLETE' || dto.status === 'ERROR' || dto.status === 'CANCELLED') {
        updateData.completedAt = new Date();
      }
      if (dto.status === 'RUNNING') {
        updateData.startedAt = new Date();
      }
    }
    if (dto.finalReport !== undefined) updateData.finalReport = dto.finalReport;
    if (dto.startedAt !== undefined) updateData.startedAt = new Date(dto.startedAt);
    if (dto.completedAt !== undefined) updateData.completedAt = new Date(dto.completedAt);

    return this.prisma.feasibilityRun.update({
      where: { id: run.id },
      data: updateData,
      include: { stages: { orderBy: { stageNumber: 'asc' } } },
    });
  }

  async cancelRun(projectId: string) {
    const run = await this.prisma.feasibilityRun.findFirst({
      where: { projectId, status: { in: ['RUNNING', 'PENDING'] } },
      orderBy: { version: 'desc' },
    });

    if (!run) {
      return { cancelled: false, reason: 'No running run found' };
    }

    return this.prisma.feasibilityRun.update({
      where: { id: run.id },
      data: { status: 'CANCELLED' },
      include: {
        stages: {
          orderBy: { stageNumber: 'asc' },
        },
      },
    });
  }

  async exportReportToDisk(
    projectId: string,
    customExportPath?: string,
  ): Promise<{ folderPath: string; mdFile: string; htmlFile: string }> {
    // Load project + latest completed run
    const project = await this.prisma.project.findUnique({ where: { id: projectId } });
    if (!project) throw new NotFoundException(`Project ${projectId} not found`);

    const run = await this.prisma.feasibilityRun.findFirst({
      where: { projectId, status: 'COMPLETE' },
      orderBy: { version: 'desc' },
    });
    if (!run || !run.finalReport) {
      throw new NotFoundException('No completed report found for this project');
    }

    const exportDir = resolveExportDir(customExportPath);

    // Slugify project title for folder name
    const slug = project.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    const folderPath = path.join(exportDir, slug);
    fs.mkdirSync(folderPath, { recursive: true });

    // Write markdown
    const mdFile = path.join(folderPath, `${slug}-feasibility.md`);
    fs.writeFileSync(mdFile, run.finalReport, 'utf-8');

    // Build self-contained HTML — sanitize before writing to disk
    const bodyHtml = sanitizeHtml(marked(run.finalReport) as string);
    const html = this.buildHtmlDoc(bodyHtml, `${project.title} — Feasibility Report`);
    const htmlFile = path.join(folderPath, `${slug}-feasibility.html`);
    fs.writeFileSync(htmlFile, html, 'utf-8');

    return { folderPath, mdFile, htmlFile };
  }

  private htmlEscape(s: string): string {
    return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  }

  private buildHtmlDoc(bodyHtml: string, title: string): string {
    const safeTitle = this.htmlEscape(title);
    return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${safeTitle}</title>
<style>
  :root { --bg: #0f1117; --surface: #1a1d27; --border: #2a2d3a; --text: #e2e8f0; --muted: #94a3b8; --accent: #3b82f6; }
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { background: var(--bg); color: var(--text); font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 15px; line-height: 1.7; padding: 40px 20px; }
  .container { max-width: 860px; margin: 0 auto; }
  h1 { font-size: 2em; font-weight: 700; color: #f1f5f9; margin-bottom: 0.4em; }
  h2 { font-size: 1.4em; font-weight: 600; color: #cbd5e1; margin: 1.8em 0 0.6em; border-bottom: 1px solid var(--border); padding-bottom: 0.3em; }
  h3 { font-size: 1.15em; font-weight: 600; color: #cbd5e1; margin: 1.4em 0 0.5em; }
  h4 { font-size: 1em; font-weight: 600; color: #94a3b8; margin: 1.2em 0 0.4em; }
  p { margin: 0.75em 0; }
  ul, ol { margin: 0.75em 0 0.75em 1.5em; }
  li { margin: 0.3em 0; }
  strong { color: #f1f5f9; font-weight: 600; }
  em { color: #94a3b8; }
  code { background: #1e2130; color: #93c5fd; padding: 0.15em 0.4em; border-radius: 4px; font-size: 0.88em; }
  pre { background: #1e2130; padding: 1em 1.2em; border-radius: 8px; overflow-x: auto; margin: 1em 0; }
  pre code { background: none; padding: 0; }
  blockquote { border-left: 3px solid var(--accent); padding-left: 1em; color: var(--muted); margin: 1em 0; }
  table { border-collapse: collapse; width: 100%; margin: 1em 0; font-size: 0.9em; }
  th { background: #1e2130; color: #cbd5e1; font-weight: 600; text-align: left; padding: 8px 12px; border: 1px solid var(--border); }
  td { padding: 7px 12px; border: 1px solid var(--border); color: var(--text); }
  tr:nth-child(even) td { background: #161923; }
  hr { border: none; border-top: 1px solid var(--border); margin: 2em 0; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
</style>
</head>
<body>
<div class="container">
${bodyHtml}
<hr style="margin-top: 3rem;">
<p style="font-size: 0.8rem; color: #6b7280; line-height: 1.5; margin-top: 1rem;">
  <strong style="color: #9ca3af;">Disclaimer:</strong> This report was generated by PatentForge, an open-source AI-powered patent landscape research tool. It is intended for informational and educational purposes only. This report does not constitute legal advice. No attorney-client relationship is created by this report. The author of this tool is not a lawyer. The AI system that generated this analysis is not a lawyer. Patent law is complex and fact-specific, and AI-generated analysis may contain errors, omissions, or hallucinated references — including fabricated patent numbers, inaccurate legal citations, and incorrect statutory interpretations presented with high confidence. Before making any filing, licensing, enforcement, or investment decisions based on this report, consult a registered patent attorney.
</p>
</div>
</body>
</html>`;
  }

  async getDocxBuffer(projectId: string): Promise<{ buffer: Buffer; filename: string }> {
    const project = await this.prisma.project.findUnique({ where: { id: projectId } });
    if (!project) throw new NotFoundException(`Project ${projectId} not found`);

    const run = await this.prisma.feasibilityRun.findFirst({
      where: { projectId, status: 'COMPLETE' },
      orderBy: { version: 'desc' },
    });
    if (!run) throw new NotFoundException('No completed report found');

    // Use finalReport if available, otherwise fall back to stage 6 output
    let reportText = run.finalReport;
    if (!reportText) {
      const stage6 = await this.prisma.feasibilityStage.findFirst({
        where: { feasibilityRunId: run.id, stageNumber: 6, status: 'COMPLETE' },
      });
      reportText = stage6?.outputText ?? null;
    }
    if (!reportText) throw new NotFoundException('No completed report found');

    const paragraphs = parseMarkdownToDocxParagraphs(reportText);

    // Append legal disclaimer watermark
    paragraphs.push(new Paragraph({ text: '' }));
    paragraphs.push(
      new Paragraph({
        children: [new TextRun({ text: '---', color: '6B7280', size: 16 })],
      }),
    );
    paragraphs.push(
      new Paragraph({
        children: [
          new TextRun({ text: 'Disclaimer: ', bold: true, color: '6B7280', size: 16, font: 'Calibri' }),
          new TextRun({
            text: 'This report was generated by PatentForge, an open-source AI-powered patent landscape research tool. It is intended for informational and educational purposes only. This report does not constitute legal advice. No attorney-client relationship is created by this report. The author of this tool is not a lawyer. The AI system that generated this analysis is not a lawyer. Patent law is complex and fact-specific, and AI-generated analysis may contain errors, omissions, or hallucinated references — including fabricated patent numbers, inaccurate legal citations, and incorrect statutory interpretations presented with high confidence. Before making any filing, licensing, enforcement, or investment decisions based on this report, consult a registered patent attorney.',
            color: '6B7280',
            size: 16,
            font: 'Calibri',
          }),
        ],
      }),
    );

    const draftHeader = new Header({
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new TextRun({
              text: 'DRAFT — NOT LEGAL ADVICE — AI-GENERATED RESEARCH ONLY',
              color: 'B0B0B0',
              size: 16,
              font: 'Calibri',
              bold: true,
            }),
          ],
        }),
      ],
    });

    const draftFooter = new Footer({
      children: [
        new Paragraph({
          alignment: AlignmentType.CENTER,
          children: [
            new TextRun({
              text: 'Generated by PatentForge · Not legal advice · Consult a patent attorney before acting',
              color: 'B0B0B0',
              size: 14,
              font: 'Calibri',
            }),
          ],
        }),
      ],
    });

    const doc = new Document({
      creator: 'PatentForge',
      title: `${project.title} — Feasibility Report`,
      numbering: ORDERED_LIST_NUMBERING,
      sections: [{
        properties: {
          page: {
            margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          },
        },
        headers: { default: draftHeader },
        footers: { default: draftFooter },
        children: paragraphs,
      }],
    });

    const buffer = await Packer.toBuffer(doc);
    const slug = project.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    return { buffer, filename: `${slug}-feasibility.docx` };
  }

  async getAllRuns(projectId: string) {
    const project = await this.prisma.project.findUnique({ where: { id: projectId } });
    if (!project) throw new NotFoundException(`Project ${projectId} not found`);

    const runs = await this.prisma.feasibilityRun.findMany({
      where: { projectId },
      orderBy: { version: 'desc' },
      include: {
        stages: { select: { estimatedCostUsd: true } },
      },
    });

    return runs.map((run) => ({
      id: run.id,
      version: run.version,
      status: run.status,
      startedAt: run.startedAt,
      completedAt: run.completedAt,
      totalCostUsd: run.stages.reduce((sum: number, s: { estimatedCostUsd?: number | null }) => sum + (s.estimatedCostUsd ?? 0), 0),
    }));
  }

  async updateRunStatus(runId: string, status: string, finalReport?: string) {
    const data: Prisma.FeasibilityRunUpdateInput = { status };
    if (finalReport !== undefined) data.finalReport = finalReport;
    if (status === 'COMPLETE' || status === 'ERROR' || status === 'CANCELLED') {
      data.completedAt = new Date();
    }

    return this.prisma.feasibilityRun.update({
      where: { id: runId },
      data,
      include: {
        stages: {
          orderBy: { stageNumber: 'asc' },
        },
      },
    });
  }
}
