#!/usr/bin/env bash
# PatentForgeLocal — Hardware Detection Script (Linux)
# Detects AMD GPU/NPU capabilities and writes configuration to .env.hardware
# Called by install scripts before starting services.
#
# Reference: docs/AMD-Ryzen-GPU-NPU-Inference.md

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HARDWARE_ENV_FILE="$PROJECT_ROOT/.env.hardware"

echo "# Auto-detected hardware configuration" > "$HARDWARE_ENV_FILE"
echo "# Generated by scripts/detect_hardware.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$HARDWARE_ENV_FILE"

echo ""
echo "=== PatentForgeLocal Hardware Detection ==="
echo ""

# ─── CPU Detection ────────────────────────────────────────────────────────────
CPU_MODEL=$(grep -m1 "model name" /proc/cpuinfo | cut -d: -f2 | xargs)
echo "CPU: $CPU_MODEL"
echo "PATENTFORGELOCAL_CPU_MODEL=\"$CPU_MODEL\"" >> "$HARDWARE_ENV_FILE"

PLATFORM="unknown"
NPU_TOPS=0

if echo "$CPU_MODEL" | grep -qiE "Ryzen AI (Max|MAX)"; then
    PLATFORM="strix_halo"
    NPU_TOPS=50
    echo "Platform: AMD Ryzen AI Max (Strix Halo)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen AI [0-9]+ [0-9]+(HX|HS|U|H)"; then
    PLATFORM="strix_krackan"
    NPU_TOPS=50
    echo "Platform: AMD Ryzen AI 300/400 (Strix Point / Gorgon Point)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 8[0-9]{3}"; then
    PLATFORM="hawk_point"
    NPU_TOPS=16
    echo "Platform: AMD Ryzen 8000 (Hawk Point)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 7[0-9]{3}(H|U|HS)"; then
    PLATFORM="phoenix"
    NPU_TOPS=16
    echo "Platform: AMD Ryzen 7000 Mobile (Phoenix)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen 9 (7945|8945)HX"; then
    PLATFORM="dragon_range"
    NPU_TOPS=0
    echo "Platform: Dragon Range — weak iGPU (610M, not suitable for inference)"
elif echo "$CPU_MODEL" | grep -qiE "Ryzen [579] 9[0-9]{3}"; then
    PLATFORM="granite_ridge"
    NPU_TOPS=0
    echo "Platform: Ryzen 9000 Desktop (Granite Ridge — no iGPU)"
fi

echo "PATENTFORGELOCAL_PLATFORM=\"$PLATFORM\"" >> "$HARDWARE_ENV_FILE"
echo "PATENTFORGELOCAL_NPU_TOPS=$NPU_TOPS" >> "$HARDWARE_ENV_FILE"

# ─── Check for discrete NVIDIA GPU ───────────────────────────────────────────
NVIDIA_GPU=false
if command -v nvidia-smi &>/dev/null; then
    NVIDIA_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
    if [ -n "$NVIDIA_NAME" ]; then
        NVIDIA_GPU=true
        NVIDIA_VRAM=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2>/dev/null | head -1 || echo "0")
        echo "NVIDIA GPU: $NVIDIA_NAME (${NVIDIA_VRAM} MB VRAM)"
        echo "PATENTFORGELOCAL_NVIDIA_GPU=\"$NVIDIA_NAME\"" >> "$HARDWARE_ENV_FILE"
        echo "PATENTFORGELOCAL_NVIDIA_VRAM_MB=$NVIDIA_VRAM" >> "$HARDWARE_ENV_FILE"
        echo "Ollama will use NVIDIA CUDA automatically"
    fi
fi
echo "PATENTFORGELOCAL_NVIDIA_GPU_PRESENT=$NVIDIA_GPU" >> "$HARDWARE_ENV_FILE"

# ─── AMD GPU Detection via ROCm ──────────────────────────────────────────────
GPU_ENABLED=false
GFX_VERSION=""
HSA_OVERRIDE=""
GPU_CU_COUNT=0

# Skip AMD iGPU config if NVIDIA discrete is present — Ollama prefers CUDA
if [ "$NVIDIA_GPU" = true ]; then
    echo "NVIDIA GPU present — skipping AMD iGPU configuration"
    GPU_ENABLED=true  # NVIDIA handles it
elif command -v rocm-smi &>/dev/null; then
    echo "ROCm found — querying AMD GPU..."

    if command -v rocminfo &>/dev/null; then
        GFX_RAW=$(rocminfo 2>/dev/null | grep -i "Name:" | grep -i "gfx" | head -1 | awk '{print $NF}' || true)
        echo "Detected GFX target: ${GFX_RAW:-unknown}"
    fi

    case "$PLATFORM" in
        strix_halo)
            GFX_VERSION="11.5.1"
            HSA_OVERRIDE="11.5.1"
            GPU_CU_COUNT=40
            ;;
        strix_krackan)
            GFX_VERSION="11.5.1"
            HSA_OVERRIDE="11.5.1"
            CU_DETECT=$(cat /sys/class/drm/card*/device/pp_num_cu 2>/dev/null | head -1 || echo "16")
            GPU_CU_COUNT=${CU_DETECT:-16}
            if [ "$GPU_CU_COUNT" -le 12 ]; then
                GFX_VERSION="11.5.0"
                HSA_OVERRIDE="11.5.0"
            fi
            ;;
        hawk_point|phoenix)
            GFX_VERSION="11.0.0"
            HSA_OVERRIDE="11.0.0"
            CU_DETECT=$(cat /sys/class/drm/card*/device/pp_num_cu 2>/dev/null | head -1 || echo "12")
            GPU_CU_COUNT=${CU_DETECT:-12}
            if [ "$GPU_CU_COUNT" -le 8 ]; then
                HSA_OVERRIDE="11.0.2"
                GFX_VERSION="11.0.2"
            fi
            ;;
        dragon_range)
            echo "WARNING: Dragon Range iGPU (Radeon 610M, 2 CU) — not suitable for inference"
            echo "If a discrete GPU is present, ROCm will use it automatically"
            ;;
        granite_ridge)
            echo "WARNING: No iGPU on Granite Ridge — CPU inference only unless discrete GPU present"
            ;;
    esac

    # Check VRAM UMA allocation
    VRAM_BYTES=$(cat /sys/class/drm/card*/device/mem_info_vram_total 2>/dev/null | head -1 || echo "0")
    VRAM_GB=$((VRAM_BYTES / 1073741824))
    echo "Reported iGPU VRAM: ${VRAM_GB} GB"

    UMA_THRESHOLD=4
    case "$PLATFORM" in
        strix_halo)         UMA_THRESHOLD=16 ;;
        strix_krackan)      UMA_THRESHOLD=8  ;;
        hawk_point|phoenix) UMA_THRESHOLD=4  ;;
    esac

    if [ "$VRAM_GB" -lt "$UMA_THRESHOLD" ] && [ "$PLATFORM" != "granite_ridge" ] && [ "$PLATFORM" != "dragon_range" ]; then
        echo ""
        echo "WARNING: iGPU VRAM allocation (${VRAM_GB} GB) is below recommended (${UMA_THRESHOLD} GB)"
        echo "To improve performance, enter BIOS/UEFI and set:"
        echo "  Advanced > AMD CBS > NBIO > UMA Frame Buffer Size = ${UMA_THRESHOLD}G or higher"
        echo ""
    fi

    if [ -e /dev/kfd ] && [ "$PLATFORM" != "granite_ridge" ] && [ "$PLATFORM" != "dragon_range" ]; then
        GPU_ENABLED=true
        echo "GPU accessible via /dev/kfd — ROCm GPU inference ENABLED"
        echo "GFX override: HSA_OVERRIDE_GFX_VERSION=$HSA_OVERRIDE"
    else
        if [ "$PLATFORM" != "granite_ridge" ] && [ "$PLATFORM" != "dragon_range" ]; then
            echo "WARNING: /dev/kfd not found — GPU not accessible"
            echo "Run the following then reboot:"
            echo "  sudo usermod -aG render,video \$USER"
            echo "  sudo modprobe amdgpu"
        fi
        echo "Falling back to CPU inference"
    fi
else
    echo "ROCm not installed — CPU inference only"
    if [ "$PLATFORM" != "granite_ridge" ] && [ "$PLATFORM" != "dragon_range" ] && [ "$PLATFORM" != "unknown" ]; then
        echo "To enable GPU acceleration:"
        echo "  sudo amdgpu-install --usecase=rocm"
        echo "  sudo usermod -aG render,video \$USER"
        echo "  sudo reboot"
    fi
fi

echo "PATENTFORGELOCAL_GPU_ENABLED=$GPU_ENABLED" >> "$HARDWARE_ENV_FILE"
echo "PATENTFORGELOCAL_GPU_CU_COUNT=$GPU_CU_COUNT" >> "$HARDWARE_ENV_FILE"
echo "PATENTFORGELOCAL_GFX_VERSION=\"$GFX_VERSION\"" >> "$HARDWARE_ENV_FILE"
echo "PATENTFORGELOCAL_HSA_OVERRIDE=\"$HSA_OVERRIDE\"" >> "$HARDWARE_ENV_FILE"

# ─── NPU Detection ───────────────────────────────────────────────────────────
NPU_AVAILABLE=false

if [ -e /dev/accel/accel0 ] || lsmod 2>/dev/null | grep -q "amdxdna"; then
    NPU_AVAILABLE=true
    echo "NPU: XDNA driver detected — ${NPU_TOPS} TOPS available"
    echo "     (Ollama does not currently use the NPU — reserved for future ONNX integration)"
else
    if [ "$NPU_TOPS" -gt 0 ]; then
        echo "NPU: Your CPU supports XDNA (${NPU_TOPS} TOPS) but driver not loaded"
        echo "     Install kernel 6.11+ and amdxdna driver for NPU access"
    else
        echo "NPU: Not present on this platform"
    fi
fi

echo "PATENTFORGELOCAL_NPU_AVAILABLE=$NPU_AVAILABLE" >> "$HARDWARE_ENV_FILE"

# ─── RAM Detection ───────────────────────────────────────────────────────────
TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
TOTAL_RAM_GB=$((TOTAL_RAM_KB / 1024 / 1024))
echo ""
echo "RAM: ${TOTAL_RAM_GB} GB"

if [ "$TOTAL_RAM_GB" -lt 32 ]; then
    echo "WARNING: Minimum 32 GB RAM recommended. Found: ${TOTAL_RAM_GB} GB"
    echo "PatentForgeLocal may not run well with less than 32 GB."
fi

RECOMMENDED_MODEL="gemma4:12b"
if [ "$TOTAL_RAM_GB" -ge 48 ]; then
    RECOMMENDED_MODEL="gemma4:27b"
fi

echo "PATENTFORGELOCAL_TOTAL_RAM_GB=$TOTAL_RAM_GB" >> "$HARDWARE_ENV_FILE"
echo "PATENTFORGELOCAL_RECOMMENDED_MODEL=\"$RECOMMENDED_MODEL\"" >> "$HARDWARE_ENV_FILE"

# ─── Disk Detection ──────────────────────────────────────────────────────────
DISK_FREE_GB=$(df -BG "$PROJECT_ROOT" | tail -1 | awk '{print $4}' | tr -d 'G')
echo "Disk free: ${DISK_FREE_GB} GB"

if [ "$DISK_FREE_GB" -lt 50 ]; then
    echo "WARNING: Less than 50 GB free. Minimum 50 GB recommended for model storage."
fi

echo "PATENTFORGELOCAL_DISK_FREE_GB=$DISK_FREE_GB" >> "$HARDWARE_ENV_FILE"

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "=== Detection Complete ==="
echo "Platform:          $PLATFORM"
echo "GPU Enabled:       $GPU_ENABLED"
if [ "$GPU_ENABLED" = true ] && [ -n "$HSA_OVERRIDE" ]; then
    echo "GFX Override:      HSA_OVERRIDE_GFX_VERSION=$HSA_OVERRIDE"
    echo "CU Count:          $GPU_CU_COUNT"
fi
if [ "$NVIDIA_GPU" = true ]; then
    echo "NVIDIA GPU:        $NVIDIA_NAME"
fi
echo "NPU Available:     $NPU_AVAILABLE (${NPU_TOPS} TOPS)"
echo "Recommended Model: $RECOMMENDED_MODEL"
echo ""
echo "Configuration written to $HARDWARE_ENV_FILE"
