# PatentForgeLocal - Hardware Detection Script (Windows)
# Detects AMD/NVIDIA GPU and NPU capabilities, writes .env.hardware
# Called by PatentForgeLocal.ps1 before starting services.
#
# On Windows, Ollama uses DirectML automatically for AMD iGPUs -
# no ROCm configuration is needed. This script detects hardware,
# warns about suboptimal BIOS settings, and recommends models.

$ErrorActionPreference = "Continue"

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir
$HardwareEnvFile = Join-Path $ProjectRoot ".env.hardware"

$envLines = @(
    "# Auto-detected hardware configuration",
    "# Generated by scripts/detect_hardware.ps1 on $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')"
)

Write-Host ""
Write-Host "=== PatentForgeLocal Hardware Detection ===" -ForegroundColor Cyan
Write-Host ""

# ─── CPU Detection ────────────────────────────────────────────────────────────
$cpu = Get-CimInstance Win32_Processor | Select-Object -First 1
$cpuModel = $cpu.Name.Trim()
Write-Host "CPU: $cpuModel"
$envLines += "PATENTFORGELOCAL_CPU_MODEL=`"$cpuModel`""

$platform = "unknown"
$npuTops = 0

if ($cpuModel -match "Ryzen AI (Max|MAX)") {
    $platform = "strix_halo"
    $npuTops = 50
    Write-Host "Platform: AMD Ryzen AI Max (Strix Halo)"
}
elseif ($cpuModel -match "Ryzen AI \d+ \d+(HX|HS|U|H)") {
    $platform = "strix_krackan"
    $npuTops = 50
    Write-Host "Platform: AMD Ryzen AI 300/400 (Strix Point / Gorgon Point)"
}
elseif ($cpuModel -match "Ryzen [579] 8\d{3}") {
    $platform = "hawk_point"
    $npuTops = 16
    Write-Host "Platform: AMD Ryzen 8000 (Hawk Point)"
}
elseif ($cpuModel -match "Ryzen [579] 7\d{3}(H|U|HS)") {
    $platform = "phoenix"
    $npuTops = 16
    Write-Host "Platform: AMD Ryzen 7000 Mobile (Phoenix)"
}
elseif ($cpuModel -match "Ryzen 9 (7945|8945)HX") {
    $platform = "dragon_range"
    $npuTops = 0
    Write-Host "Platform: Dragon Range - weak iGPU (610M, not suitable for inference)"
}
elseif ($cpuModel -match "Ryzen [579] 9\d{3}") {
    $platform = "granite_ridge"
    $npuTops = 0
    Write-Host "Platform: Ryzen 9000 Desktop (Granite Ridge - no iGPU)"
}

$envLines += "PATENTFORGELOCAL_PLATFORM=`"$platform`""
$envLines += "PATENTFORGELOCAL_NPU_TOPS=$npuTops"

# ─── GPU Detection ───────────────────────────────────────────────────────────
$gpus = Get-CimInstance Win32_VideoController
$nvidiaGpu = $false
$nvidiaName = ""
$amdGpuName = ""
$amdVramBytes = 0
$gpuEnabled = $false

foreach ($gpu in $gpus) {
    $name = $gpu.Name
    if ($name -match "NVIDIA") {
        $nvidiaGpu = $true
        $nvidiaName = $name
        $nvidiaVramMB = [math]::Round($gpu.AdapterRAM / 1MB)
        Write-Host "NVIDIA GPU: $name ($nvidiaVramMB MB)"
        $envLines += "PATENTFORGELOCAL_NVIDIA_GPU=`"$name`""
        $envLines += "PATENTFORGELOCAL_NVIDIA_VRAM_MB=$nvidiaVramMB"
        $gpuEnabled = $true
    }
    elseif ($name -match "Radeon" -and $name -notmatch "610M") {
        $amdGpuName = $name
        # Win32_VideoController.AdapterRAM is uint32, overflows at 4 GB.
        # For AMD iGPUs with UMA > 4 GB, read the QWORD from the registry.
        $amdVramBytes = [uint64]$gpu.AdapterRAM
        try {
            $regPath = "HKLM:\SYSTEM\CurrentControlSet\Control\Class\{4d36e968-e325-11ce-bfc1-08002be10318}"
            Get-ChildItem $regPath -ErrorAction SilentlyContinue | ForEach-Object {
                $driverDesc = (Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue).DriverDesc
                if ($driverDesc -eq $name) {
                    $qwMem = (Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue).'HardwareInformation.qwMemorySize'
                    if ($qwMem -and $qwMem -gt $amdVramBytes) {
                        $amdVramBytes = [uint64]$qwMem
                    }
                }
            }
        } catch { }
        $amdVramGB = [math]::Round($amdVramBytes / 1GB, 1)
        Write-Host "AMD iGPU: $name ($amdVramGB GB VRAM)"
        $gpuEnabled = $true

        # Check UMA allocation and warn if low
        $umaThreshold = 4
        switch ($platform) {
            "strix_halo"    { $umaThreshold = 16 }
            "strix_krackan" { $umaThreshold = 8  }
            "hawk_point"    { $umaThreshold = 4  }
            "phoenix"       { $umaThreshold = 4  }
        }

        if ($amdVramGB -lt $umaThreshold) {
            Write-Host ""
            Write-Host "WARNING: iGPU VRAM ($amdVramGB GB) below optimal ($umaThreshold GB)" -ForegroundColor Yellow
            Write-Host "  To improve inference speed, enter BIOS/UEFI and increase:" -ForegroundColor Yellow
            Write-Host "  Advanced > AMD CBS > NBIO > UMA Frame Buffer Size = ${umaThreshold}G+" -ForegroundColor Yellow
            Write-Host ""
        }

        $envLines += "PATENTFORGELOCAL_AMD_GPU=`"$name`""
        $envLines += "PATENTFORGELOCAL_AMD_VRAM_GB=$amdVramGB"
    }
    elseif ($name -match "610M") {
        Write-Host "AMD iGPU: $name (2 CU - not suitable for inference)" -ForegroundColor Yellow
    }
}

$envLines += "PATENTFORGELOCAL_NVIDIA_GPU_PRESENT=$($nvidiaGpu.ToString().ToLower())"
$envLines += "PATENTFORGELOCAL_GPU_ENABLED=$($gpuEnabled.ToString().ToLower())"

if ($nvidiaGpu) {
    Write-Host "Ollama will use NVIDIA CUDA automatically" -ForegroundColor Green
}
elseif ($amdGpuName) {
    Write-Host "Ollama will use AMD DirectML automatically (no configuration needed)" -ForegroundColor Green
}
else {
    Write-Host "No suitable GPU detected - Ollama will use CPU inference" -ForegroundColor Yellow
}

# ─── NPU Detection ───────────────────────────────────────────────────────────
$npuAvailable = $false

# Check for AMD XDNA NPU via PnP devices (filter to AMD devices only)
$npuDevice = Get-PnpDevice -ErrorAction SilentlyContinue |
    Where-Object { $_.FriendlyName -match "NPU" -and $_.Manufacturer -match "AMD|Advanced Micro" }
if (-not $npuDevice) {
    $npuDevice = Get-PnpDevice -FriendlyName "*XDNA*" -ErrorAction SilentlyContinue
}
if (-not $npuDevice) {
    $npuDevice = Get-PnpDevice -ErrorAction SilentlyContinue |
        Where-Object { $_.FriendlyName -match "AI Engine" -and $_.Manufacturer -match "AMD|Advanced Micro" }
}

if ($npuDevice) {
    $npuAvailable = $true
    $npuName = ($npuDevice | Select-Object -First 1).FriendlyName
    Write-Host "NPU: $npuName detected - $npuTops TOPS"
    Write-Host "     (Ollama does not currently use the NPU - reserved for future ONNX integration)" -ForegroundColor DarkGray
    $envLines += "PATENTFORGELOCAL_NPU_NAME=`"$npuName`""
}
else {
    if ($npuTops -gt 0) {
        Write-Host "NPU: CPU supports XDNA ($npuTops TOPS) but device not detected"
        Write-Host "     Check Device Manager for AMD AI Engine or install AMD NPU driver"
    }
    else {
        Write-Host "NPU: Not present on this platform"
    }
}

$envLines += "PATENTFORGELOCAL_NPU_AVAILABLE=$($npuAvailable.ToString().ToLower())"

# ─── RAM Detection ───────────────────────────────────────────────────────────
$totalRamBytes = (Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory
$totalRamGB = [math]::Round($totalRamBytes / 1GB)
Write-Host ""
Write-Host "RAM: $totalRamGB GB"

if ($totalRamGB -lt 32) {
    Write-Host "WARNING: Minimum 32 GB RAM recommended. Found: $totalRamGB GB" -ForegroundColor Yellow
    Write-Host "PatentForgeLocal may not run well with less than 32 GB." -ForegroundColor Yellow
}

$recommendedModel = "gemma4:12b"
if ($totalRamGB -ge 48) {
    $recommendedModel = "gemma4:27b"
}

$envLines += "PATENTFORGELOCAL_TOTAL_RAM_GB=$totalRamGB"
$envLines += "PATENTFORGELOCAL_RECOMMENDED_MODEL=`"$recommendedModel`""

# ─── Disk Detection ──────────────────────────────────────────────────────────
$drive = (Get-Item $ProjectRoot).PSDrive
$diskFreeGB = [math]::Floor((Get-PSDrive $drive.Name).Free / 1GB)
Write-Host "Disk free: $diskFreeGB GB"

if ($diskFreeGB -lt 50) {
    Write-Host "WARNING: Less than 50 GB free. Minimum 50 GB recommended for model storage." -ForegroundColor Yellow
}

$envLines += "PATENTFORGELOCAL_DISK_FREE_GB=$diskFreeGB"

# ─── Write .env.hardware ─────────────────────────────────────────────────────
$envLines | Out-File -FilePath $HardwareEnvFile -Encoding utf8

# ─── Summary ─────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "=== Detection Complete ===" -ForegroundColor Cyan
Write-Host "Platform:          $platform"
Write-Host "GPU Enabled:       $gpuEnabled"
if ($nvidiaGpu) {
    Write-Host "NVIDIA GPU:        $nvidiaName"
}
if ($amdGpuName) {
    Write-Host "AMD iGPU:          $amdGpuName"
}
Write-Host "NPU Available:     $npuAvailable ($npuTops TOPS)"
Write-Host "Recommended Model: $recommendedModel"
Write-Host ""
Write-Host "Configuration written to $HardwareEnvFile"
