"""
Export patent application to DOCX and Markdown formats.

DOCX export follows USPTO 37 CFR 1.52 formatting requirements:
- US Letter (8.5" x 11"), margins: top 0.75", left 1.0", right/bottom 0.75"
- Times New Roman, 12pt, 1.5 line spacing
- Sequential [NNNN] paragraph numbering (Background, Summary, Figures, Detailed Description)
- Claims and Abstract NOT paragraph-numbered
- Claims and Abstract each start on a new page
- Centered page numbers in footer
- Diagonal watermark on every page
- Markdown bold/italic rendered as Word formatting
"""

from __future__ import annotations
import io
import re
from datetime import datetime

from lxml import etree
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from .models import ExportRequest


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_PARAGRAPH_NUM_RE = re.compile(r"^\[\d{4}\]\s*")


def _strip_existing_numbers(text: str) -> str:
    """Remove any existing [NNNN] paragraph number prefixes from text."""
    lines: list[str] = []
    for line in text.split("\n"):
        lines.append(_PARAGRAPH_NUM_RE.sub("", line))
    return "\n".join(lines)


def _add_formatted_runs(paragraph, text: str) -> None:
    """Convert markdown **bold** and *italic* markers into Word runs."""
    # Split on bold (**...**) and italic (*...*) patterns.
    # Bold must be matched before italic since ** contains *.
    parts = re.split(r"(\*\*[^*]+\*\*|\*[^*]+\*)", text)
    for part in parts:
        if not part:
            continue
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        elif part.startswith("*") and part.endswith("*"):
            run = paragraph.add_run(part[1:-1])
            run.italic = True
        else:
            run = paragraph.add_run(part)
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)


def _add_numbered_paragraph(doc: Document, text: str, num: int) -> int:
    """Add a paragraph with USPTO-style [NNNN] numbering and return next num."""
    p = doc.add_paragraph()
    # Bold number run
    run_num = p.add_run(f"[{num:04d}]    ")
    run_num.bold = True
    run_num.font.name = "Times New Roman"
    run_num.font.size = Pt(12)
    # Formatted text runs
    _add_formatted_runs(p, text)
    return num + 1


def _add_section_heading(doc: Document, title: str) -> None:
    """Add a section heading in bold, centered, Times New Roman 12pt."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(title.upper())
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(12)


def _add_page_numbers(doc: Document) -> None:
    """Add centered page numbers to the document footer on every section."""
    for section in doc.sections:
        footer = section.footer
        footer.is_linked_to_previous = False
        p = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # "Generated by PatentForge — Not Legal Advice" line
        run_disclaimer = p.add_run("Generated by PatentForge \u2014 Not Legal Advice\n")
        run_disclaimer.italic = True
        run_disclaimer.font.name = "Times New Roman"
        run_disclaimer.font.size = Pt(8)

        # PAGE field code for page number
        run1 = p.add_run()
        fld_begin = OxmlElement("w:fldChar")
        fld_begin.set(qn("w:fldCharType"), "begin")
        run1._element.append(fld_begin)

        run2 = p.add_run()
        instr = OxmlElement("w:instrText")
        instr.set(qn("xml:space"), "preserve")
        instr.text = " PAGE "
        run2._element.append(instr)

        run3 = p.add_run()
        fld_end = OxmlElement("w:fldChar")
        fld_end.set(qn("w:fldCharType"), "end")
        run3._element.append(fld_end)


def _add_watermark(doc: Document) -> None:
    """Add a draft warning banner in the header on every page.

    Uses a visible light-gray text banner rather than VML WordArt,
    which has inconsistent rendering across Word versions.
    """
    watermark_text = (
        "DRAFT \u2014 NOT LEGAL ADVICE \u2014 MUST BE REVIEWED BY PATENT ATTORNEY"
    )

    for section in doc.sections:
        header = section.header
        header.is_linked_to_previous = False

        # Add bordered warning banner
        p = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Add top/bottom border to the paragraph for visual separation
        pPr = p._element.get_or_add_pPr()
        pBdr = OxmlElement("w:pBdr")
        for border_name in ["top", "bottom"]:
            border = OxmlElement(f"w:{border_name}")
            border.set(qn("w:val"), "single")
            border.set(qn("w:sz"), "4")
            border.set(qn("w:space"), "1")
            border.set(qn("w:color"), "C0C0C0")
            pBdr.append(border)
        pPr.append(pBdr)

        run = p.add_run(watermark_text)
        run.font.name = "Times New Roman"
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0xA0, 0xA0, 0xA0)
        run.bold = True


def _setup_page(doc: Document) -> None:
    """Configure page size, margins, and default font per USPTO 37 CFR 1.52."""
    # Page layout
    for section in doc.sections:
        section.page_width = Inches(8.5)
        section.page_height = Inches(11)
        section.top_margin = Inches(0.75)
        section.bottom_margin = Inches(0.75)
        section.left_margin = Inches(1.0)
        section.right_margin = Inches(0.75)

    # Default Normal style
    style = doc.styles["Normal"]
    font = style.font
    font.name = "Times New Roman"
    font.size = Pt(12)
    pf = style.paragraph_format
    pf.line_spacing = 1.5


def _paragraphs_from_content(content: str) -> list[str]:
    """Split section content into individual paragraphs, stripping empties."""
    content = _strip_existing_numbers(content)
    paras = content.split("\n\n")
    result: list[str] = []
    for p in paras:
        text = p.strip()
        if text:
            result.append(text)
    return result


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def _add_draft_header_footer(doc: Document) -> None:
    """Add 'DRAFT — NOT LEGAL ADVICE' header and footer to every page."""
    for section in doc.sections:
        # Header
        header = section.header
        header.is_linked_to_previous = False
        hp = header.paragraphs[0] if header.paragraphs else header.add_paragraph()
        hp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        hr = hp.add_run("DRAFT — NOT LEGAL ADVICE — AI-GENERATED RESEARCH ONLY")
        hr.bold = True
        hr.font.size = Pt(8)
        hr.font.color.rgb = RGBColor(176, 176, 176)
        hr.font.name = "Calibri"
        # Footer
        footer = section.footer
        footer.is_linked_to_previous = False
        fp = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
        fr = fp.add_run("Generated by PatentForge · Not legal advice · Consult a patent attorney before acting")
        fr.font.size = Pt(7)
        fr.font.color.rgb = RGBColor(176, 176, 176)
        fr.font.name = "Calibri"


def export_docx(req: ExportRequest) -> bytes:
    """Generate a Word document formatted per USPTO 37 CFR 1.52."""
    doc = Document()
    _setup_page(doc)
    _add_draft_header_footer(doc)

    # ── Title Page ──────────────────────────────────────────────────────
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(req.title or "Patent Application")
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(18)

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle.add_run("Patent Application")
    sub_run.font.name = "Times New Roman"
    sub_run.font.size = Pt(14)

    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    d_run = date_para.add_run(f"Generated: {datetime.now().strftime('%Y-%m-%d')}")
    d_run.font.name = "Times New Roman"
    d_run.font.size = Pt(12)

    disclaimer = doc.add_paragraph()
    disclaimer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    disc_run = disclaimer.add_run(
        "\nIMPORTANT: This is an AI-generated research draft. "
        "It must be reviewed by a registered patent attorney before filing."
    )
    disc_run.italic = True
    disc_run.font.name = "Times New Roman"
    disc_run.font.size = Pt(9)

    doc.add_page_break()

    # ── Sequential paragraph counter ────────────────────────────────────
    para_num = 1

    # Sections that receive [NNNN] paragraph numbering
    numbered_sections: list[tuple[str, str]] = [
        ("Background of the Invention", req.background or ""),
        ("Summary of the Invention", req.summary or ""),
        ("Brief Description of the Drawings", req.figure_descriptions or ""),
    ]

    for heading, content in numbered_sections:
        if not content.strip():
            continue
        _add_section_heading(doc, heading)
        for para_text in _paragraphs_from_content(content):
            para_num = _add_numbered_paragraph(doc, para_text, para_num)

    # ── Detailed Description (page break, paragraph numbered) ──────────
    dd_content = (req.detailed_description or "").strip()
    if dd_content:
        doc.add_page_break()
        _add_section_heading(doc, "Detailed Description of Preferred Embodiments")
        for para_text in _paragraphs_from_content(dd_content):
            para_num = _add_numbered_paragraph(doc, para_text, para_num)

    # ── Claims (page break, NOT paragraph numbered) ────────────────────
    claims_content = (req.claims or "").strip()
    if claims_content:
        doc.add_page_break()
        _add_section_heading(doc, "Claims")
        for para_text in _paragraphs_from_content(claims_content):
            p = doc.add_paragraph()
            _add_formatted_runs(p, para_text)

    # ── Abstract (page break, NOT paragraph numbered) ──────────────────
    abstract_content = (req.abstract or "").strip()
    if abstract_content:
        doc.add_page_break()
        _add_section_heading(doc, "Abstract of the Disclosure")
        # Abstract is a single paragraph (strip existing numbers)
        clean = _strip_existing_numbers(abstract_content).strip()
        p = doc.add_paragraph()
        _add_formatted_runs(p, clean)

    # ── Information Disclosure Statement (if present) ──────────────────
    ids_content = (req.ids_table or "").strip()
    if ids_content:
        _add_section_heading(doc, "Information Disclosure Statement")
        for para_text in ids_content.split("\n\n"):
            text = para_text.strip()
            if text:
                p = doc.add_paragraph()
                _add_formatted_runs(p, text)

    # ── Cross-References (if present) ──────────────────────────────────
    xref_content = (req.cross_references or "").strip()
    if xref_content:
        _add_section_heading(doc, "Cross-Reference to Related Applications")
        for para_text in _paragraphs_from_content(xref_content):
            p = doc.add_paragraph()
            _add_formatted_runs(p, para_text)

    # ── Page numbers + footer disclaimer ───────────────────────────────
    _add_page_numbers(doc)

    # ── Watermark ──────────────────────────────────────────────────────
    _add_watermark(doc)

    # Serialize
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def export_markdown(req: ExportRequest) -> str:
    """Generate a Markdown document from the application sections."""
    parts = []

    parts.append(f"# {req.title or 'Patent Application'}\n")
    parts.append(f"*Generated: {datetime.now().strftime('%Y-%m-%d')}*\n")
    parts.append("*AI-generated research draft — must be reviewed by a registered patent attorney.*\n")

    sections = [
        ("Cross-Reference to Related Applications", req.cross_references),
        ("Background of the Invention", req.background),
        ("Summary of the Invention", req.summary),
        ("Detailed Description of Preferred Embodiments", req.detailed_description),
        ("Claims", req.claims),
        ("Abstract of the Disclosure", req.abstract),
        ("Brief Description of the Drawings", req.figure_descriptions),
        ("Information Disclosure Statement", req.ids_table),
    ]

    for heading, content in sections:
        if not content or not content.strip():
            continue
        parts.append(f"\n## {heading}\n")
        parts.append(content.strip())
        parts.append("")

    return "\n".join(parts)
