/**
 * Single source of truth for legal disclaimer text.
 * All components should import from here rather than duplicating the text.
 */

export const DISCLAIMER_SHORT =
  'Research tool — not legal advice. This AI-generated output is for informational and educational purposes only. ' +
  'It does not constitute legal advice or create an attorney-client relationship. ' +
  'Always consult a registered patent attorney before making filing, licensing, or enforcement decisions.';

export const DISCLAIMER_LONG =
  'This report was generated by PatentForge, an open-source AI-powered patent landscape research tool. ' +
  'It is intended for informational and educational purposes only. This report does not constitute legal advice. ' +
  'No attorney-client relationship is created by this report. The author of this tool is not a lawyer. ' +
  'The AI system that generated this analysis is not a lawyer. Patent law is complex and fact-specific, ' +
  'and AI-generated analysis may contain errors, omissions, or hallucinated references — including fabricated ' +
  'patent numbers, inaccurate legal citations, and incorrect statutory interpretations presented with high confidence. ' +
  'Before making any filing, licensing, enforcement, or investment decisions based on this report, ' +
  'consult a registered patent attorney.';
